openai:
  api_key: "your-openai-api-key"
  base_url: "https://models.inference.ai.azure.com"
  model: "gpt-4o"

google:
  api_keys:
    - "your-google-api-key1"
    - "your-google-api-key"
  model: "gemini-1.5-flash"